[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "stopper"
version = "0.1.0"
description = "package"
dependencies = ["pytest"]

[tool.hatch.build.targets.wheel]
packages = ["src/stopper"] 